// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJdk2pmeAl_VKe-3oJS_xHPeGPiMlOZk',
    appId: '1:568990476948:web:ac7007e4c35167eeeee281',
    messagingSenderId: '568990476948',
    projectId: 'travller-98697',
    authDomain: 'travller-98697.firebaseapp.com',
    storageBucket: 'travller-98697.firebasestorage.app',
    measurementId: 'G-GS2SDZ9XZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EmwADsan0UGhETD9t3DBcumhyB0K6FY',
    appId: '1:568990476948:android:19f92cb7155105f7eee281',
    messagingSenderId: '568990476948',
    projectId: 'travller-98697',
    storageBucket: 'travller-98697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoKWF_WzvsdjdqY6awdKA0QBHJBhZIzM8',
    appId: '1:568990476948:ios:984217712c12cf99eee281',
    messagingSenderId: '568990476948',
    projectId: 'travller-98697',
    storageBucket: 'travller-98697.firebasestorage.app',
    iosBundleId: 'com.example.travller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoKWF_WzvsdjdqY6awdKA0QBHJBhZIzM8',
    appId: '1:568990476948:ios:984217712c12cf99eee281',
    messagingSenderId: '568990476948',
    projectId: 'travller-98697',
    storageBucket: 'travller-98697.firebasestorage.app',
    iosBundleId: 'com.example.travller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJdk2pmeAl_VKe-3oJS_xHPeGPiMlOZk',
    appId: '1:568990476948:web:b8b3cef1c7475688eee281',
    messagingSenderId: '568990476948',
    projectId: 'travller-98697',
    authDomain: 'travller-98697.firebaseapp.com',
    storageBucket: 'travller-98697.firebasestorage.app',
    measurementId: 'G-46KL1D7QHC',
  );
}
